image: montefuscolo/ssh

before_script:
  - eval $(ssh-agent -s)
  - mkdir -m 700 -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa

test:
  script:
    - test -s wp-content/themes/its-rio/assets/css/its.css
    - test -s wp-content/themes/its-rio/assets/css/wp-map.css
    - test -s wp-content/themes/its-rio/assets/js/its.js

deploy:
  script:
  - ssh -o StrictHostKeyChecking=no itsrio@itsrio.net git -C /srv/itsrio.net/wordpress pull
